### ISSUE TITLE
Uncaught TypeError: Cannot read property 'valid' of undefined

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#117]
https://github.com/davidkpiano/react-redux-form/blob/master/src/components/form-component.js#L93-L94

I'm getting this error when I try to submit my form. Code below.

```javascript
    <Form model="track" onSubmit={track => submit(track)}>
      <Field model="track.name">
        <input />
      </Field>

      <input type="submit" />
    </Form>
```

**Comment by davidkpiano** [comment]
This is probably because you don't have a form reducer, although I fixed that check I believe... are you on the latest version?

**Comment by ffxsam** [comment]
You're totally right - and I forgot to come back and post that. It didn't used to be a requirement to use the form reducer, correct? And now it is?

**Comment by davidkpiano** [comment]
No, it's not a requirement. RRF should check if a form state exists. If it doesn't, that's totally fine -- it'll just calculate the validity from the `<Form>` validators before submitting.

Can you see if that works with the latest version?

**Comment by ffxsam** [comment]
Sure, I'll check it out when I get a chance and report back.

**Comment by bkudria** [comment]
I'm still seeing this issue if the form does not have any custom validators either. Is this a valid use-case for RRF?

**Comment by davidkpiano** [comment]
> I'm still seeing this issue if the form does not have any custom validators either. Is this a valid use-case for RRF?

Yes, should be, RRF handles more than just validation. Can you share the code that can demonstrate the issue?

**Comment by bkudria** [comment]
I'll try to work up a minimal case.

**Comment by davidkpiano** [comment]
@ffxsam and @bkudria, this has been recently fixed in `react-redux-form@0.9.14` :smile: 

The form reducer is not required. See this issue for more info: https://github.com/davidkpiano/react-redux-form/issues/139
